### ISSUE TITLE
【DB】DB設計

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-api#1]
# 完成形
ER図でまとめる！Draw.ioで！

**Comment by mizucoffee** [comment]
![dj drawio](https://user-images.githubusercontent.com/9247699/142854895-34fc8278-3da9-483a-ab6b-88d148b09454.png)

**Comment by penguin4731** [comment]
管理アカウントを全部Googleログインにしたほうが設計コストダウンになるかな
ルームを管理する人が1人か問題
メリット: MCで引き継ぐ・CMがしゃべっている間にCAがチェックするとかできそう
デメリット: 実装コスト重め（ソケットなりで接続を結ぶ必要がある。）

**Comment by penguin4731** [comment]
- UserとRoomを多対他
- Letterの下にSongをつくって、複数持てるようにする

**Comment by konnyakuken** [comment]
![dj_ER](https://user-images.githubusercontent.com/75003683/145827159-0bf91288-8b43-4159-baff-bfa306b82b69.png)

https://drive.google.com/file/d/1nbgix6dHA-GaC3fdcXJi06jSAK9SYKW-/view?usp=sharing
