### ISSUE TITLE
MC/adminのEmailも一緒に返してほしい

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-api#106]
# 概要

全然急ぎではないですが、このAPIと一緒にEmailも返してもらえるとたすかります！

https://www.postman.com/lit-kansai-dj/workspace/dj-system-workspace/request/18983315-094f5c12-819e-4f9b-bdf9-b186ed363f2d

# 目的

# タスク

- [ ] 細かいタスクに分解できているなら書き出す

# ゴール

# 参考リンク

**Comment by mizucoffee** [comment]
@penguin4731 こちら対応しました！
今回のコミットより、スコープにemailを要求するようにしたので、既存のAPIキーではemailが取得出来ません。
取得できなかった場合はemailにnullが入ります。
