### ISSUE TITLE
音楽サービスとアカウント連携してないとルームを作成できない仕様にしたい

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-api#108]
# 概要

MCがルーム作成するときに、Spotify とアカウント連携できてないとルーム作成を拒否してほしい

# 目的

ルーム管理画面の方でバグがでるので、そもそも連携していないユーザーに対してルーム作成できないようにしたい

# タスク

- [ ] 細かいタスクに分解できているなら書き出す

# ゴール

# 参考リンク

**Comment by mizucoffee** [comment]
forbidden出すようにしました
