### ISSUE TITLE
【ルーム管理】リクエスト送った後に、待つ秒数をMCが設定できるようにする

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-api#124]
今、デフォルト（5分）で指定しているリクエスト後のクーリングタイムをMCが自分で設定できるようにする

**Comment by konnyakuken** [comment]
待ち時間を送るタイミングについて

ユーザーが曲リクエストを送る
↓
サーバーから成功
そのタイミングに待ち時間が出るイメージで実装する

この辺りを使うと良さそう
[Retry-After](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Retry-After)
