### ISSUE TITLE
ドキュメント修正

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai/dj_system-api#140]
Swaggerにおいて
- POST /mc/room
- GET /mc/room/{roomId}
のレスポンス形式が正しくないので修正する

**Comment by txxxxc** [comment]
ごめんこれ自分が報告したやつやと思うんやけど、/mc/room/{roomId}はレスポンスの形式あってるっぽいので修正しなくて大丈夫です....!🙇‍♂️
( room/{roomId}と勘違いしてた )

**Comment by konnyakuken** [comment]
GET /mc/room/{roomId}は間違っていないので、POST /mc/roomを修正する
