### ISSUE TITLE
/mc/room と /mc/room/{room_id} の時に apple music playlistを見る用のURLが欲しい

### ISSUE THREAD

**Issue by 9-sho-5** [lit-kansai/dj_system-api#177]
# 概要
applemusicのplaylist idとブラウザで見るURLが全然違う

# ゴール
resでアクセスできるURLを返す or ブラウザ用の`pl.〇〇`を返す

# 参考リンク

**Comment by gassi4731** [comment]
これ、Spotifyも同じ仕様にしてほしいかも！

**Comment by 9-sho-5** [comment]
pl.〇〇作るには、applemusicブラウザで共有リンク作る必要ある
